import math

'''Constants'''
INFECTION_RATE = float(0.8)
SOCIAL_INFLUENCE_FACTOR = float(0.5)
CLOSENESS_FACTOR = float(0.6)
PERCIEVED_INFECTION_RATE = INFECTION_RATE
RECOVERY_RATE = float(0.312)
N = 788
COST_RATIO = float(0.1)
PROB_OF_ANTI_VAC = 0.3
RESPONSIVENESS = 5

I_START = math.floor(max(N * 0.01, 1))
